cors:
  allowed:
    origins: ${CC_CORS_ALLOWED_ORIGINS}
server:
    port: 8081
spring:
  data:
    mongodb:
      uri: ${CC_DATABASE_URL}
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: https://www.googleapis.com/oauth2/v1/tokeninfo
          client-id: ${CC_OAUTH2_CLIENT_ID}
          client-secret: ${CC_OAUTH2_CLIENT_SECRET}
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
logging:
  level:
    org:
      springframework:
        security: DEBUG