cors:
  allowed:
    origins: ${CORS_ALLOWED_ORIGINS}
database:
  uri: ${DATABASE_URI}
  username: ${DATABASE_USER}
  password: ${DATABASE_PASSWORD}
identity_provider:
  uri: ${IDENTITY_PROVIDER_URI}
server:
    port: 8081
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${IDENTITY_PROVIDER_URI}/auth/realms/demo
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
logging:
  level:
    reactor:
    org:
      springframework:
        security: DEBUG
        r2dbc: DEBUG
debug: true